import re, json

INPUT = 'src/data/results.ts'
OUTPUT = 'src/data/results.ts'

with open(INPUT, encoding='utf-8') as f:
    text = f.read()

# Only apply replacements inside backtick template literals
# Strategy: find content: `...` blocks and replace only inside those

replacements = [
    # Multi-word phrases first (longest match)
    ('Luc luong lao dong', 'Lực lượng lao động'),
    ('nang suat LĐ', 'năng suất LĐ'),
    ('nang suat nhan to tong hop', 'năng suất nhân tố tổng hợp'),
    ('nhan to tong hop', 'nhân tố tổng hợp'),
    ('ham san xuat', 'hàm sản xuất'),
    ('san xuat', 'sản xuất'),
    ('chi phi co hoi', 'chi phí cơ hội'),
    ('chi phi cong bang', 'chi phí công bằng'),
    ('chi phi', 'chi phí'),
    ('cong bang', 'công bằng'),
    ('Dong gop cua', 'Đóng góp của'),
    ('Dong gop', 'Đóng góp'),
    ('dong gop', 'đóng góp'),
    ('Phan ra tang truong', 'Phân rã tăng trưởng'),
    ('Phan ra', 'Phân rã'),
    ('phan ra', 'phân rã'),
    ('Tang truong binh quan', 'Tăng trưởng bình quân'),
    ('Tang truong GDP', 'Tăng trưởng GDP'),
    ('Tang truong', 'Tăng trưởng'),
    ('tang truong', 'tăng trưởng'),
    ('tang tu', 'tăng từ'),
    ('tang len', 'tăng lên'),
    ('tang them', 'tăng thêm'),
    ('Du bao san luong', 'Dự báo sản lượng'),
    ('Du bao', 'Dự báo'),
    ('du bao', 'dự báo'),
    ('san luong', 'sản lượng'),
    ('sai so', 'sai số'),
    ('Sai so', 'Sai số'),
    ('Phan bo toi uu', 'Phân bổ tối ưu'),
    ('Phan bo', 'Phân bổ'),
    ('phan bo', 'phân bổ'),
    ('toi uu', 'tối ưu'),
    ('Toi uu', 'Tối ưu'),
    ('Rang buoc', 'Ràng buộc'),
    ('rang buoc', 'ràng buộc'),
    ('kha thi', 'khả thi'),
    ('Kha thi', 'Khả thi'),
    ('Giai bang', 'Giải bằng'),
    ('Giai lai', 'Giải lại'),
    ('giai bang', 'giải bằng'),
    ('giai nguoc', 'giải ngược'),
    ('Gia doi ngung', 'Giá đối ngẫu'),
    ('gia doi ngung', 'giá đối ngẫu'),
    ('Giai thich', 'Giải thích'),
    ('giai thich', 'giải thích'),
    ('Phan tich do nhay', 'Phân tích độ nhạy'),
    ('Phan tich', 'Phân tích'),
    ('phan tich', 'phân tích'),
    ('Do nhay', 'Độ nhạy'),
    ('do nhay', 'độ nhạy'),
    ('Kich ban', 'Kịch bản'),
    ('kich ban', 'kịch bản'),
    ('So sanh', 'So sánh'),
    ('so sanh', 'so sánh'),
    ('chenh lech', 'chênh lệch'),
    ('Chenh lech', 'Chênh lệch'),
    ('dinh nghia', 'định nghĩa'),
    ('Luu y', 'Lưu ý'),
    ('luu y', 'lưu ý'),
    ('Xu huong', 'Xu hướng'),
    ('xu huong', 'xu hướng'),
    ('He so goc', 'Hệ số góc'),
    ('He so', 'Hệ số'),
    ('he so', 'hệ số'),
    ('Ty trong', 'Tỷ trọng'),
    ('ty trong', 'tỷ trọng'),
    ('Ty le', 'Tỷ lệ'),
    ('ty le', 'tỷ lệ'),
    ('ty gia', 'tỷ giá'),
    ('nghin ty VND', 'nghìn tỷ VND'),
    ('nghin ty', 'nghìn tỷ'),
    ('trieu nguoi', 'triệu người'),
    ('Von vat chat', 'Vốn vật chất'),
    ('von tich luy', 'vốn tích lũy'),
    ('Lao dong', 'Lao động'),
    ('lao dong', 'lao động'),
    ('Nhan luc so', 'Nhân lực số'),
    ('nhan luc', 'nhân lực'),
    ('So hoa', 'Số hóa'),
    ('so hoa', 'số hóa'),
    ('Du lieu', 'Dữ liệu'),
    ('du lieu', 'dữ liệu'),
    ('doc tu', 'đọc từ'),
    ('Tinh Solow', 'Tính Solow'),
    ('Thuc te', 'Thực tế'),
    ('thuc te', 'thực tế'),
    ('trung binh', 'trung bình'),
    ('Trung binh', 'Trung bình'),
    ('binh quan', 'bình quân'),
    ('Tong dau tu', 'Tổng đầu tư'),
    ('Cac du an', 'Các dự án'),
    ('cac', 'các'),
    ('du an', 'dự án'),
    ('Du an', 'Dự án'),
    ('duoc', 'được'),
    ('chon', 'chọn'),
    ('ngan sach', 'ngân sách'),
    ('Ngan sach', 'Ngân sách'),
    ('Bat buoc', 'Bắt buộc'),
    ('loi ich ky vong', 'lợi ích kỳ vọng'),
    ('Loi ich', 'Lợi ích'),
    ('loi ich', 'lợi ích'),
    ('ky vong', 'kỳ vọng'),
    ('xac suat', 'xác suất'),
    ('Xac suat', 'Xác suất'),
    ('hoan thanh', 'hoàn thành'),
    ('tien do', 'tiến độ'),
    ('Chuan hoa', 'Chuẩn hóa'),
    ('chuan hoa', 'chuẩn hóa'),
    ('trong so', 'trọng số'),
    ('Trong so', 'Trọng số'),
    ('mac dinh', 'mặc định'),
    ('thay doi', 'thay đổi'),
    ('Thay doi', 'Thay đổi'),
    ('xep hang', 'xếp hạng'),
    ('Xep hang', 'Xếp hạng'),
    ('on dinh', 'ổn định'),
    ('Dinh huong', 'Định hướng'),
    ('dinh huong', 'định hướng'),
    ('bao trum', 'bao trùm'),
    ('uu tien', 'ưu tiên'),
    ('chuyen gia', 'chuyên gia'),
    ('nhat quan', 'nhất quán'),
    ('chi so', 'chỉ số'),
    ('Chi so', 'Chỉ số'),
    ('tieu chi', 'tiêu chí'),
    ('nganh', 'ngành'),
    ('Nganh', 'Ngành'),
    ('vung', 'vùng'),
    ('Vung', 'Vùng'),
    ('ha tang', 'hạ tầng'),
    ('cong nghe', 'công nghệ'),
    ('dao tao', 'đào tạo'),
    ('Dao tao', 'Đào tạo'),
    ('ky su', 'kỹ sư'),
    ('ban dan', 'bán dẫn'),
    ('thong minh', 'thông minh'),
    ('thong ke', 'thống kê'),
    ('quoc gia', 'quốc gia'),
    ('Quoc gia', 'Quốc gia'),
    ('hieu qua', 'hiệu quả'),
    ('phat thai', 'phát thải'),
    ('Phat thai', 'Phát thải'),
    ('moi truong', 'môi trường'),
    ('rui ro', 'rủi ro'),
    ('Rui ro', 'Rủi ro'),
    ('ton thuong', 'tổn thương'),
    ('de ton thuong', 'dễ tổn thương'),
    ('viec lam', 'việc làm'),
    ('nguong', 'ngưỡng'),
    ('dao tao lai', 'đào tạo lại'),
    ('chinh sach', 'chính sách'),
    ('Chinh sach', 'Chính sách'),
    ('quy hoach', 'quy hoạch'),
    ('Quy hoach', 'Quy hoạch'),
    ('ngau nhien', 'ngẫu nhiên'),
    ('tich hop', 'tích hợp'),
    ('Tich hop', 'Tích hợp'),
    ('Nguyen mau', 'Nguyên mẫu'),
    ('nguyen mau', 'nguyên mẫu'),
    ('Nghiem', 'Nghiệm'),
    ('nghiem', 'nghiệm'),
    ('thoa hiep', 'thỏa hiệp'),
    ('tap Pareto', 'tập Pareto'),
    ('da muc tieu', 'đa mục tiêu'),
    ('muc tieu', 'mục tiêu'),
    ('Chien luoc', 'Chiến lược'),
    ('chien luoc', 'chiến lược'),
    ('Trang thai', 'Trạng thái'),
    ('phuc hoi', 'phục hồi'),
    ('phuc loi', 'phúc lợi'),
    ('loai bo', 'loại bỏ'),
    ('loai tru', 'loại trừ'),
    ('tien quyet', 'tiên quyết'),
    ('dong hoc', 'động học'),
    ('Toi da hoan', 'Tối đa hóa'),
    ('Toi da', 'Tối đa'),
    ('cai dat', 'cài đặt'),
    ('Cai dat', 'Cài đặt'),
    ('thu vien', 'thư viện'),
    ('bo qua', 'bỏ qua'),
    ('chay', 'chạy'),
    ('dau tien', 'đầu tiên'),
    ('tu dong', 'tự động'),
    ('xu ly', 'xử lý'),
    ('hien', 'hiện'),
    ('luu', 'lưu'),
    ('san sang', 'sẵn sàng'),
    ('con thieu', 'còn thiếu'),
    ('KHONG', 'KHÔNG'),
    ('khong', 'không'),
    # diacritics for direction words
    ('Cuu Long', 'Cửu Long'),
]

def replace_in_backtick_strings(text, replacements):
    """Only replace Vietnamese text inside backtick string content."""
    parts = re.split(r'(`[^`]*`)', text)
    result = []
    for part in parts:
        if part.startswith('`') and part.endswith('`'):
            # Inside a backtick string - apply replacements
            content = part
            for old, new in replacements:
                content = content.replace(old, new)
            result.append(content)
        else:
            # Outside backtick strings (TypeScript code) - leave untouched
            result.append(part)
    return ''.join(result)

fixed = replace_in_backtick_strings(text, replacements)

with open(OUTPUT, 'w', encoding='utf-8') as f:
    f.write(fixed)

# Verify no TS keywords were corrupted
with open(OUTPUT, encoding='utf-8') as f:
    check = f.read()
if 'expởrt' in check or 'frởm' in check or 'intểrface' in check:
    print("ERROR: TypeScript keywords corrupted! Reverting.")
else:
    print(f"Done. Applied replacements inside backtick strings only.")
